### ISSUE TITLE
cannot import name 'replace_file'

### ISSUE THREAD

**Issue by Gemini77** [lbe0613/LET#2]
what's wrong with 
ImportError:cannot import name 'replace_file' from ‘mxnet.gluon.utils’

**Comment by lbe0613** [comment]
> what's wrong with
> ImportError:cannot import name 'replace_file' from ‘mxnet.gluon.utils’

Maybe it's because the mxnet version is different, so please use mxnet==1.5.1

**Comment by GoddessLuBoYan** [comment]
I download mxnet-cu100==1.6.0 from https://dist.mxnet.io/python/all and it works.
However, I can not work with mxnet-cu100==1.5.1

**Comment by lbe0613** [comment]
I revisited my environment, the mxnet version I used is 1.5.1.post0.
Also, I created a new conda environment and installed mxnet by pip install mxnet-cu100==1.5.1 from Tsinghua Open Source Mirror (https://pypi.tuna.tsinghua.edu.cn/simple). It works well, so I decide to close this issue.
